### ISSUE TITLE
Extension not working when no folder is open in the workspace

### ISSUE THREAD

**Issue by samishchandra** [LaurentTreguier/vscode-uncrustify#55]
Can we make the extension work even though no folder is open in the workspace.. currently the extension would only work on a file if a folder is open in the workspace.. also can we make the extension work for non saved files.

**Comment by samishchandra** [comment]
@LaurentTreguier ^.. thanks for working on the extension.

**Comment by LaurentTreguier** [comment]
It should be fixed with version 2.17.6 👍

**Comment by samishchandra** [comment]
Still seeing this error on update.

![image](https://user-images.githubusercontent.com/2313133/68158654-e77a1300-ff04-11e9-9e70-bdac88e9b774.png)

**Comment by samishchandra** [comment]
On a unsaved file, getting the following error.

![image](https://user-images.githubusercontent.com/2313133/68159034-cb2aa600-ff05-11e9-87ec-a1e677a97f1a.png)

**Comment by LaurentTreguier** [comment]
Version 2.17.7 should fix it for good; but do re-open if this isn't the case

**Comment by samishchandra** [comment]
@LaurentTreguier amazing.. thanks for the quick turnaround. This is fixed now.
